name: cat_trivia
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  retrofit: ^3.0.1+1
  equatable: ^2.0.3
  get_it: ^7.2.0
  hive: ^2.2.3
  path_provider: ^2.0.11
  json_annotation: ^4.6.0
  intl: ^0.17.0
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  retrofit_generator: ^4.0.3+1
  hive_generator: ^1.1.3
  build_runner: ^2.2.0
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true